### ISSUE TITLE
Game keeps crashing on linux

### ISSUE THREAD

**Issue by tropicthedev** [maruohon/malilib#101]
Hi I keep crashing on linux whenever I try to use Litematica or Tweakeroo. It happens whenever i try to run an action or execute a key bind, the logs are below.

[crash-2022-09-25_17.12.58-client.txt](https://github.com/maruohon/malilib/files/9670798/crash-2022-09-25_17.12.58-client.txt)
[crash-2022-09-26_20.33.24-client.txt](https://github.com/maruohon/malilib/files/9670799/crash-2022-09-26_20.33.24-client.txt)
[crash-2022-09-27_22.35.06-client.txt](https://github.com/maruohon/malilib/files/9670800/crash-2022-09-27_22.35.06-client.txt)
[crash-2022-09-28_22.51.40-client.txt](https://github.com/maruohon/malilib/files/9670801/crash-2022-09-28_22.51.40-client.txt)
[crash-2022-09-28_22.54.10-client.txt](https://github.com/maruohon/malilib/files/9670802/crash-2022-09-28_22.54.10-client.txt)

**Comment by vacla** [comment]
@TypicalTropic make sure you are using all official mod versions and latest version that only masa uploaded on curseforge since if you mix the community version, you will very likely crash

**Comment by tropicthedev** [comment]
@vacla I do believe that all the mods are up to date I just installed them from curse forge this week.

**Comment by tropicthedev** [comment]
Hmmm im not sure if I had an outdated version of Malilib but i just redownloaded all the mods and it seems to be working now
