### ISSUE TITLE
incomplete mod set?

### ISSUE THREAD

**Issue by NotNiceKun** [maruohon/malilib#102]
i don't found this version
- 0.9.0?
- 0.11.0?
![image](https://user-images.githubusercontent.com/92991362/193973409-4211bae3-0ac3-46ed-998b-a159b43426f5.png)

**Comment by maruohon** [comment]
Which MC version are you on, 1.17.1? Just get the latest version of both mods for your MC version from CurseForge.

The error basically says that you need version `0.10.0-dev.25` or newer of malilib, but older than 0.11. And currently you don't have malilib at all.
