### ISSUE TITLE
Download misslabed

### ISSUE THREAD

**Issue by Kerbal-Man** [maruohon/malilib#103]
![image](https://user-images.githubusercontent.com/100152985/200131611-16127b77-4cd6-49be-b9dc-1039cf1cb805.png)
Here it says its for version 1.19 yet its not compatible with 1.19 and i had to go scrolling down the ancient days of modding to get 
![image](https://user-images.githubusercontent.com/100152985/200131662-323e590a-2ddb-48ef-9cef-24081d26870b.png)

**Comment by vacla** [comment]
This is not a mislabel, this is just how curseforge shows it.

**Comment by maruohon** [comment]
That main title label there basically means `1.19.x` and it will just show the latest version there is for any of the 1.19 minor versions. There is nothing I can do about that label. I can only label the individual uploaded files for which MC versions they work on. And those labels you can see on the Files page and when you click on each uploaded file/version.
