### ISSUE TITLE
Fabric Installation crashes on 1.19.3

### ISSUE THREAD

**Issue by nathanmcmullen** [maruohon/malilib#108]
Hey there,

After updating all my fabric mods for 1.19.3, starting the game generated a cryptic crash report on what looks like Minecraft's main thread (i.e. not referencing fabric or mixins, etc.), linked [here](https://paste.sh/Zp_zXdk2#klV1rYlbztnurpru-LVDl72T). After a painstaking process of elimination through each mod in my collection, I identified the offending mod to be Malilib. The crash persisted after removing all unrelated and dependent mods - the linked crash report was generated with Malilib being the only mod loaded (or rather failing to load). The error also persisted when loaded with FabricAPI.

Further, some fabric resource mixin error was also generated in the console just before the crash. I can't tell if it is related, so I included it in the pastebin in case it helped debugging.

This error occurred using the latest Fabric Loader (0.14.11) on Windows 10 (Patch 21H2) and as per the crash report Java version 17.0.3.

Please let me know what might be the issue!

**Comment by kosma** [comment]
Please post your mod list.

**Comment by nathanmcmullen** [comment]
As I described in the original post, the crash and associated report were generated with only MaLiLib in the mods folder. 

However, this is the list that I would usually have installed if it helps:

- Appleskin 2.4.1
- Bad Packets 0.3.3
- Boosted Brightness 2.1.2
- Carpet Mod 1.4.91
- Iris 1.4.6
- Lithium 0.10.4
- Sodium 0.4.6
- Logical Zoom 0.0.18
- Mod Menu 5.0.2
- WTHIT 6.1.0
- Xaeros Minimap 22.16.3
- Xaros Worldmap 1.28.4

**Comment by Coathar** [comment]
What version of malilib are you using? You should be using [malilib-fabric-1.19.3-0.14.0.jar](https://www.curseforge.com/minecraft/mc-mods/malilib/files/4147598)

**Comment by nathanmcmullen** [comment]
Thank you for the link, that fixed the issue right away. The curseforge page has the 0.14.0 edition marked as a beta and as such was not the highlighted build for download. I should've checked for something like that!

Thank you for your prompt replies and my apologies for such a trivial issue.
