### ISSUE TITLE
Not able to input "Scroll Up/Down" as hotkey

### ISSUE THREAD

**Issue by ErikderFreak** [maruohon/malilib#112]
Issue: 
     When trying to input either Scroll up or Scroll down into a hotkey it won't input.
     Instead it will go out of the selection and scroll up or down the hotkey config GUI. 

How to replicate:
1. Open any hotkey config from mods based on malilib (or malilib itself).
2. Select a hotkey to configure.
3. a) Try inputting mouse Scroll up or Scroll down
b) Try inputting a combo of some key and Scroll up or Scroll down

**Comment by ErikderFreak** [comment]
To be sure it's not the mouse, I did a mouseScrollDebug and the Scroll input seems to be correct:
"[03:37:07] [Render thread/INFO]: time: 37B1, tick: 5D4C - xOffset: 0.0, yOffset: 1.0, discrete: false, sensitivity: 1.0, amount: 1.0"

**Comment by maruohon** [comment]
The old code simply did not hook up the mouse scrolls to the hotkey system. The post-rewrite system does however. So in the new code you can use scrolls as hotkeys.

(The new code is in the `liteloader_1.12.2` branch, and it's only in the 1.12.2 LiteLoader releases as of now, plus the "rewrite early port 3" build for 1.19.2, which isn't used by any released mods yet.)

**Comment by ErikderFreak** [comment]
Oh ok.
Good to know. 
Thank you
