### ISSUE TITLE
Immersive Portals Issue

### ISSUE THREAD

**Issue by Drew-Chase** [maruohon/malilib#116]
# Issue
When in the nether while looking through the Immersive Portal to the Overworld my FPS drops from 60 to 20 and the debugger it says malilib_renderworldlast is using ~27% total resources

## Debug Tree
- root
- gameRenderer
- level
- render_portal_total
- render_portal_content
- malilib_renderworldlast

# Instance Information
## Versions
- Minecraft: 1.19.3
- Fabric: 0.14.14
- JDK : 17.0.4.101
<details>
<summary><h2> Modlist</h2></summary>
<p>
<ul>
<li> AdditionalStructures-1.19.x-(v.4.1.1).jar</li>
<li> advancementinfo-1.19.3-fabric0.68.1-1.3.1.jar</li>
<li> AmbientSounds_FABRIC_v5.2.17_mc1.19.3.jar</li>
<li> Amplified_Nether_v1.2.jar</li>
<li> animatica-0.5+1.19.jar</li>
<li> antighost-1.19.3-fabric0.68.1-1.1.5.jar</li>
<li> anvilrestoration-1.19.3-2.0.jar</li>
<li> appleskin-fabric-mc1.19.3-2.4.2.jar</li>
<li> architectury-7.1.70-fabric.jar</li>
<li> AttributeFix-Fabric-1.19.3-18.0.1.jar</li>
<li> authme-mc1.19.3-5.0.0.jar</li>
<li> badpackets-fabric-0.3.4.jar</li>
<li> balm-fabric-1.19.3-5.0.2.jar</li>
<li> BeaconOverhaul-1.7.5+1.19.3.jar</li>
<li> beautifiedchatserver-1.19.3-2.2.jar</li>
<li> betterbeaconplacement-1.19.3-3.1.jar</li>
<li> betterbeds-1.3.0-1.19.3.jar</li>
<li> BetterF3-5.1.0-Fabric-1.19.3.jar</li>
<li> bettermounthud-1.2.1.jar</li>
<li> BetterPingDisplay-Fabric-1.19.3-1.1.1.jar</li>
<li> betterstats-2.2.1+1.19.3.jar</li>
<li> BetterTags-1.19.3-Fabric-v1.0.jar</li>
<li> betterthanmending-1.3.0.jar</li>
<li> BiomeParticleWeather-v4.0.4-1.19.3-Fabric.jar</li>
<li> blur-2.6.1.jar</li>
<li> boathud-1.1.2.jar</li>
<li> Bookshelf-Fabric-1.19.3-17.0.3.jar</li>
<li> borderless-mining-1.1.6+1.19.3.jar</li>
<li> BowInfinityFix-1.19.x-fabric-2.5.0.jar</li>
<li> BuildingWands_mc1.19.3-2.6.5_beta-fabric.jar</li>
<li> Capes-1.5.1+1.19.3.jar</li>
<li> carpet-extra-1.19.3-1.4.91.jar</li>
<li> carryon-fabric-1.19.3-2.0.4.15.jar</li>
<li> cem-0.7.2.jar</li>
<li> CITResewn-1.1.3+1.19.3.jar</li>
<li> ClearDespawn-fabric-1.19.2-1.1.10.jar</li>
<li> clickadv-fabric-3.0.jar</li>
<li> clickthrough-1.19.3-fabric0.68.1-0.4.jar</li>
<li> cloth-config-9.0.94-fabric.jar</li>
<li> Clumps-fabric-1.19.3-9.0.0+16.jar</li>
<li> collective-1.19.3-6.48.jar</li>
<li> compacthelpcommand-1.19.3-2.1.jar</li>
<li> connectivity-fabric-1.19.3-3.9.jar</li>
<li> Controlling-fabric-1.19.3-10.0+9.jar</li>
<li> CosmeticArmor-1.19.3-1.4.1.jar</li>
<li> CreativeCore_FABRIC_v2.10.4_mc1.19.3.jar</li>
<li> cullleaves-fabric-3.0.3.jar</li>
<li> deathlog-0.3.1+1.19.3.jar</li>
<li> Debugify-1.19.3+1.1.jar</li>
<li> dragonloot-1.1.3.jar</li>
<li> dynamic-fps-2.2.0.jar</li>
<li> easiervillagertrading-1.19.3-fabric0.68.1-1.5.4.jar</li>
<li> EditSign-1.19.3-2.7.0.jar</li>
<li> emi_loot-0.6.1+1.19.3.jar</li>
<li> emi-0.6.4+1.19.3.jar</li>
<li> EMITrades-fabric-1.1.0+mc1.19.3.jar</li>
<li> EnchantmentDescriptions-Fabric-1.19.3-14.0.4.jar</li>
<li> endportalrecipe-1.19.3-5.0.jar</li>
<li> entity_texture_features_fabric_1.19.3-4.3.1.jar</li>
<li> entityculling-fabric-1.5.2-mc1.19.3.jar</li>
<li> EquipmentCompare-1.19.3-fabric-1.3.2.jar</li>
<li> Essential-fabric_1-19.jar</li>
<li> exordium-fabric-1.0.3-mc1.19.3.jar</li>
<li> extended-armor-bars-1.2.1.jar</li>
<li> extremesoundmuffler-3.35-fabric-1.19.3.jar</li>
<li> fabric-api-0.73.2+1.19.3.jar</li>
<li> fabric-carpet-1.19.3-1.4.96+v230201.jar</li>
<li> fabric-language-kotlin-1.9.1+kotlin.1.8.10.jar</li>
<li> fabricskyboxes-0.6.2+mc1.19.3.jar</li>
<li> fabrishot-1.9.1.jar</li>
<li> fallingleaves-1.14.5+1.19.3.jar</li>
<li> farsight-fabric-1.19-3.4.jar</li>
<li> fastback-0.8.0+1.19.3.jar</li>
<li> Fastload+1.19.3-2.6.11.jar</li>
<li> fastquit-2.1.0+1.19.3.jar</li>
<li> fat-experience-orbs-2.0.1+1.18-fabric.jar</li>
<li> ferritecore-5.1.0-fabric.jar</li>
<li> ForgeConfigAPIPort-v5.0.9-1.19.3-Fabric.jar</li>
<li> fsb-interop-1.1.4+mc1.19.3-build.30.jar</li>
<li> heartytrinkets-1.19.3-1.0.0.jar</li>
<li> hiddenrecipebook-1.19.3-4.0.jar</li>
<li> Iceberg-1.19.3-fabric-1.1.4.jar</li>
<li> ImmediatelyFast-1.1.8+1.19.3.jar</li>
<li> immersive_armors-1.5.4+1.19.3-fabric.jar</li>
<li> immersive-portals-2.5.1-mc1.19.3-fabric.jar</li>
<li> incantationem-1.2+1.19.3.jar</li>
<li> indium-1.0.14+mc1.19.3.jar</li>
<li> InventorySorter-1.8.10-1.19.3.jar</li>
<li> inventorytotem-1.19.3-3.0.jar</li>
<li> InvView-1.4.10-1.19.3+.jar</li>
<li> iris-mc1.19.3-1.5.2.jar</li>
<li> IronChests-1.7.8.jar</li>
<li> itemscroller-fabric-1.19.3-0.18.0.jar</li>
<li> jamlib-0.6.0+1.19.3.jar</li>
<li> krypton-0.2.1.jar</li>
<li> lambdynamiclights-2.2.0+1.19.3.jar</li>
<li> language-reload-1.5.4+1.19.3.jar</li>
<li> lazydfu-0.1.3.jar</li>
<li> ledger-1.2.6.jar</li>
<li> letmedespawn-1.18.x-1.19.x-fabric-1.0.2.jar</li>
<li> litematica-fabric-1.19.3-0.13.1.jar</li>
<li> litematica-printer-1.19.3-3.1.jar</li>
<li> lithium-fabric-mc1.19.3-0.10.4.jar</li>
<li> main-menu-credits-1.1.1.jar</li>
<li> malilib-fabric-1.19.3-0.14.0.jar</li>
<li> memoryleakfix-1.19.3-0.7.0.jar</li>
<li> midnightcontrols-1.7.3+1.19.3.jar</li>
<li> midnightlib-fabric-1.1.0.jar</li>
<li> minihud-fabric-1.19.3-0.25.0.jar</li>
<li> MixinConflictHelper-1.2.0.jar</li>
<li> mixintrace-1.1.1+1.17.jar</li>
<li> modelfix-1.10-fabric.jar</li>
<li> modmenu-5.0.2.jar</li>
<li> MoreAchievements-1.19.3-1.0.10.jar</li>
<li> moreadvancementsmod-1.2.2-1.19.3.jar</li>
<li> morechathistory-1.19.1-1.1.1.jar</li>
<li> moreculling-1.19.3-0.16.0.jar</li>
<li> moremcmeta-1.19.3-3.0.6-fabric.jar</li>
<li> mythicupgrades-fabric-1.6-BetaPreview3-1.19.3.jar</li>
<li> nametagtweaks-1.19.3-3.0.jar</li>
<li> netherportalfix-fabric-1.19.3-11.0.1.jar</li>
<li> no-resource-pack-warnings-1.0.0.jar</li>
<li> NoChatReports-FABRIC-1.19.3-v2.0.0.jar</li>
<li> nofade-1.18-2.0.1.jar</li>
<li> NoFog-1.3.2_1.16.5-1.19.3-fabric.jar</li>
<li> observable-4.3.1.jar</li>
<li> OfflineSkins-1.19.3-v1-fabric.jar</li>
<li> optigui-1.1.6.jar</li>
<li> owo-lib-0.10.2+1.19.3.jar</li>
<li> oxidized-1.8.0.jar</li>
<li> panorama-1.2.0 - 1.19.3.jar</li>
<li> Patchouli-1.19.3-78-FABRIC.jar</li>
<li> PetOwner-1.8.4-1.19.3+.jar</li>
<li> pistorder-mc1.19.3-v1.5.0-fabric.jar</li>
<li> Prism-1.19.3-fabric-1.0.4.jar</li>
<li> puzzle-1.4.2-1.19.3.jar</li>
<li> quickshulker-1.3.10-1.19.3.jar</li>
<li> reacharound+1.19.3-1.1.2.jar</li>
<li> reeses_sodium_options-1.4.9+mc1.19.2-build.67.jar</li>
<li> repurposed_structures-6.3.15+1.19.3-fabric.jar</li>
<li> right-click-harvest-3.1.0+1.19.3.jar</li>
<li> RingOfEnderchest-Fabric-1.19.3-rc1-1.4.5.jar</li>
<li> servertick-mc1.19-1.7.jar</li>
<li> ShowMeWhatYouGot-1.19.3-1.1.0.jar</li>
<li> smoothchunk-fabric-1.19.3-3.0.jar</li>
<li> sodium-extra-0.4.17+mc1.19.3-build.95.jar</li>
<li> sodium-fabric-mc1.19.3-0.4.9+build.23.jar</li>
<li> soundphysics-fabric-1.19.3-1.0.18.jar</li>
<li> splash_milk-1.19.3-1.3.0.jar</li>
<li> starlight-1.1.1+fabric.ae22326.jar</li>
<li> Structory-1.19-v1.3.jar</li>
<li> suggestion-tweaker-1.19.1-1.3.1-fabric.jar</li>
<li> syncmatica-1.18.2-0.3.8.jar</li>
<li> TerraBlender-fabric-1.19.3-2.1.0.139.jar</li>
<li> terrestria-5.1.1.jar</li>
<li> toms_storage_fabric-1.19.3-1.5.0.jar</li>
<li> ToolStats-Fabric-1.19.3-13.0.1.jar</li>
<li> tooltipfix-1.1.1-1.19.3.jar</li>
<li> trade-cycling-fabric-1.19.3-1.0.5.jar</li>
<li> traverse-6.1.2.jar</li>
<li> trinkets-3.5.1.jar</li>
<li> tweakeroo-fabric-1.19.3-0.15.0.jar</li>
<li> veinmining-fabric-1.0.1+1.19.3.jar</li>
<li> visuality-0.6.0.jar</li>
<li> weaponmaster-client-only-fabric-1.19.3-3.0.5.jar</li>
<li> WilderWild-1.1.13-Fabric+1.19.3.jar</li>
<li> wolf-armor-compat-1.0.3-1.19.2.jar</li>
<li> wraith-waystones-3.0.6+mc1.19.3.jar</li>
<li> wthit-fabric-6.1.4.jar</li>
<li> Xaeros_Minimap_23.1.0_Fabric_1.19.3.jar</li>
<li> XaerosWorldMap_1.28.9_Fabric_1.19.3.jar</li>
<li> YetAnotherConfigLib-2.2.0.jar</li>
<li> yosbr-0.1.1.jar</li>
<li> youre-in-grave-danger-1.5.1.jar</li>
<li> zergatul.freecam-1.5.0-fabric-1.19.3.jar</li>
<li> Zoomify-2.9.2.jar</li>
</ul>
</p>
</ details>

**Comment by maruohon** [comment]
Does the FPS recover if you toggle off MiniHUD main rendering (`H`) or Litematica main rendering (`M + R`)? If so, which one individually or both together?

**Comment by Drew-Chase** [comment]
it does not

**Comment by Drew-Chase** [comment]
Here is a video I recorded of the issue
[![LINK](https://img.youtube.com/vi/3E5rQCWDd1c/maxresdefault.jpg)](https://www.youtube.com/embed/watch?v=3E5rQCWDd1c)

**Comment by maruohon** [comment]
Are you currently using Fabulous graphics? Then try switching to Fancy to see if that slow `malilib_renderworldlast` section disappears then.

Because I just found a few lines of code in that malilib render event handler that I have no recollection what they were for... But that piece of code only runs in the Fabulous graphics mode.

If it's not that, then try taking out MiniHUD and Litematica completely, and see if that malilib section is still high up in the profiler. It shouldn't do anything without any registered mod render handlers, except if you are in Fabulous mode, where it does those couple of extra calls that I don't remember why they are there... They were probably to fix some kind of issue somewhere...

**Comment by Drew-Chase** [comment]
So I removed malilib and all mods requiring it and it issue still persists this time it says "weather" is the issue... I should have checked this first, I apologize for bothering you.

## P.S.
Love your mods!

**Comment by maruohon** [comment]
Okay. And thanks!

TBF I would pretty much expect there to be a fairly noticeable performance hit when you are essentially rendering two worlds simultaneously. It's just rather weird how it showed up in the malilib profiler section, unless it was actually malilib also (further?) slowing things down.
