### ISSUE TITLE
Minecraft Fabric 1.18.2 keeps on crashing when i press options

### ISSUE THREAD

**Issue by Spyridon-X** [maruohon/malilib#119]
Whenever I try to press the options button the game crashes. Heres the crash report:

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 3/24/23, 10:51 PM
Description: mouseClicked event handler

java.lang.NoSuchMethodError: 'net.minecraft.class_5250 net.minecraft.class_2561.method_43471(java.lang.String)'
	at net.minecraft.class_429.handler$ecd006$midnightlib$init(class_429.java:1028)
	at net.minecraft.class_429.method_25426(class_429.java)
	at net.minecraft.class_437.method_25423(class_437.java:389)
	at net.minecraft.class_310.method_1507(class_310.java:993)
	at net.minecraft.class_433.method_19840(class_433.java:62)
	at net.minecraft.class_4185.method_25306(class_4185.java:40)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:121)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:492)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:197)
	at net.minecraft.class_1041.method_15998(class_1041.java:310)
	at net.minecraft.class_310.method_1523(class_310.java:1147)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_429.handler$ecd006$midnightlib$init(class_429.java:1028)
	at net.minecraft.class_429.method_25426(class_429.java)
	at net.minecraft.class_437.method_25423(class_437.java:389)
	at net.minecraft.class_310.method_1507(class_310.java:993)
	at net.minecraft.class_433.method_19840(class_433.java:62)
	at net.minecraft.class_4185.method_25306(class_4185.java:40)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:121)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:492)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:197)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_433
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:492)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:197)
	at net.minecraft.class_1041.method_15998(class_1041.java:310)
	at net.minecraft.class_310.method_1523(class_310.java:1147)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['destinvanished'/179, l='ClientLevel', x=-5492.31, y=84.00, z=-1614.41]]
	Chunk stats: 1024, 620
	Level dimension: minecraft:overworld
	Level spawn location: World: (-5408,95,-1520), Section: (at 0,15,0 in -338,5,-95; chunk contains blocks -5408,-64,-1520 to -5393,319,-1505), Region: (-11,-3; contains chunks -352,-96 to -321,-65, blocks -5632,-64,-1536 to -5121,319,-1025)
	Level time: 29006 game time, 37949 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:407)
	at net.minecraft.class_310.method_1587(class_310.java:2376)
	at net.minecraft.class_310.method_1514(class_310.java:756)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 4128106448 bytes (3936 MiB) / 10032775168 bytes (9568 MiB) up to 12884901888 bytes (12288 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz
	Identifier: Intel64 Family 6 Model 141 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 2.50
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: Intel(R) UHD Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x9a60
	Graphics card #0 versionInfo: DriverVersion=30.0.101.1340
	Graphics card #1 name: NVIDIA GeForce RTX 3070 Laptop GPU
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x249d
	Graphics card #1 versionInfo: DriverVersion=30.0.14.7141
	Memory slot #0 capacity (MB): 32768.00
	Memory slot #0 clockSpeed (GHz): 2.93
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 32768.00
	Memory slot #1 clockSpeed (GHz): 2.93
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 74965.13
	Virtual memory used (MB): 28377.28
	Swap memory total (MB): 9728.00
	Swap memory used (MB): 0.00
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx12G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		ambientsounds: Ambiend Sounds (Fabric) 5.0.16
		architectury: Architectury 4.11.89
		attributefix: AttributeFix 14.0.2
		balm-fabric: Balm 3.2.6
		bclib: BCLib 1.4.7
		bettercombat: Better Combat 1.6.2+1.18.2
		betterend: Better End 1.1.1
		betternether: Better Nether 6.1.2
		betterthirdperson: Better Third Person 1.8.1
		bettervillage: Better village 2.1.0
		biomemakeover: Biome Makeover 1.18.2-1.4.32
		bookshelf: Bookshelf 13.2.52
		byg: Oh The Biomes You'll Go 1.4
		charm: Charm 4.4.4
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		cloth-config: Cloth Config v6 6.4.90
			cloth-basic-math: cloth-basic-math 0.6.1
		collective: Collective 6.53
		combatroll: Combat Roll 1.1.5+1.18.2
		comforts: Comforts 1.1.3-1.18.2
			cardinal-components-base: Cardinal Components API (base) 4.1.4
			cardinal-components-entity: Cardinal Components API (entities) 4.1.4
		creativecore: CreativeCore (Fabric) 2.6.12
		ctov: ChoiceTheorem's Overhauled Villages 2.9.2
		dark-enchanting: Dark Enchanting 1.0.0+1.18.2
			omega-config: OmegaConfig 1.2.3-1.18.1
		doom: Doom Fabric 4.2.40
		dungeons_arise: When Dungeons Arise 2.1.50
		dusk: Dusk Mod 1.18.2-2.1
		ecologics: Ecologics 1.7.11
		effective: Effective 1.2.1
		enchdesc: EnchantmentDescriptions 10.0.12
		enhancedcelestials: Enhanced Celestials 2.0.7
		fabric-api: Fabric API 0.75.1+1.18.2
			fabric-api-base: Fabric API Base 0.4.5+64b7c69360
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.3+2373a54560
			fabric-biome-api-v1: Fabric Biome API (v1) 8.0.6+651bcc5960
			fabric-block-api-v1: Fabric Block API (v1) 1.0.0+ee3621fc60
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.13+3ac43d9560
			fabric-command-api-v1: Fabric Command API (v1) 1.1.10+d7c144a860
			fabric-commands-v0: Fabric Commands (v0) 0.2.9+b4f4f6cd60
			fabric-containers-v0: Fabric Containers (v0) 0.1.24+d7c144a860
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.1.2+c85f2e3860
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.2+474e4f7960
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.1+ee261a3e60
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 3.0.3+9fcb91d260
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.21+489d6f8260
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.9+d7c144a860
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.20+d7c144a860
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.21+d7c144a860
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
			fabric-item-api-v1: Fabric Item API (v1) 1.6.1+a6f01b2660
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.15+91896a4960
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.12+54e5b2ec60
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.10+b4f4f6cd60
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.1+cc71601c60
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.1+1997ad1260
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.3+e747827960
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.5+cc71601c60
			fabric-models-v0: Fabric Models (v0) 0.3.7+d7c144a860
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.24+2d30af4b60
			fabric-networking-v0: Fabric Networking (v0) 0.3.11+b4f4f6cd60
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.1.4+032c981d60
			fabric-particles-v1: Fabric Particles (v1) 0.2.13+526dc1ac60
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.12+bb2e047760
			fabric-renderer-api-v1: Fabric Renderer API (v1) 0.5.0+bf48649860
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.1+03e2b68760
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.12+b4f4f6cd60
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.9+ee3621fc60
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.3+54e5b2ec60
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.14+b4f4f6cd60
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.8+54e5b2ec60
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.3+91b7aa6660
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.2+446e059560
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.11+d882b91560
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.3+1f6558e860
			fabric-textures-v0: Fabric Textures (v0) 1.0.13+3ac43d9560
			fabric-transfer-api-v1: Fabric Transfer API (v1) 1.6.4+f4563ac860
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.0+e747827960
		fabric-language-kotlin: Fabric Language Kotlin 1.9.2+kotlin.1.8.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.8.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.20.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.5.0
		fabricloader: Fabric Loader 0.14.17
		fallingleaves: Falling Leaves 1.11.1+1.18.2
		friendlyfire: FriendlyFire 11.0.3
		galosphere: Galosphere 1.18.2-1.2.1
			midnightlib: MidnightLib 0.5.2
		geckolib3: Geckolib 3.0.80
			com_eliotlash_mclib_mclib: mclib 20
		goodall: Goodall 1.0.2
		horsestatsvanilla: Horse Stats Vanilla 4.1.10
		illuminations: Illuminations 1.10.4
		indium: Indium 1.0.7+mc1.18.2
		iris: Iris 1.5.2
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre9
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		ironchests: Iron Chests 1.7.4
			libgui: LibGui 5.4.2+1.18.2
				jankson: Jankson 4.0.0+j1.2.0
					blue_endless_jankson: jankson 1.2.1
				libninepatch: LibNinePatch 1.1.0
		jade: Jade 5.99.10
		java: OpenJDK 64-Bit Server VM 17
		jei: Just Enough Items 10.2.1.1004
		lambdynlights: LambDynamicLights 2.1.0+1.17
			pride: Pride Lib 1.1.0+1.17
			spruceui: SpruceUI 3.3.0+1.17
				org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		libraryferret: Library ferret 4.0.0
		lithium: Lithium 0.10.3
		magistuarmory: Epic Knights Mod 7.5
		mca: Minecraft Comes Alive 7.4.7+1.18.2
		mcda: MC Dungeons Armors 2.0.7
		mcdw: MC Dungeons Weapons 5.0.4-1.18
			enchant_giver: Enchant Giver 1.2.1
			reach-entity-attributes: Reach Entity Attributes 2.2.0
		minecraft: Minecraft 1.18.2
		modid: Creatures Of The Snow 2.1.0+1.18.2
		mousetweaks: Mouse Tweaks 2.22
		naturalist: Naturalist 1.1.1
		player-animator: Player Animator 1.0.2+1.18
		reeses-sodium-options: Reese's Sodium Options 1.5.0+mc1.18.2-build.70
		rottencreatures: Rotten Creatures 1.0.0
		seedfix: Seed Fix 1.0.1
		simplyswords: Simply Swords 1.40-1.18.2
		smoothboot: Smooth Boot 1.18.2-1.7.0
		sodium: Sodium 0.4.1+build.15
			org_joml_joml: joml 1.10.2
		sodium-extra: Sodium Extra 0.4.18+mc1.18.2-build.98
			caffeineconfig: CaffeineConfig 1.1.0+1.17
			crowdin-translate: CrowdinTranslate 1.4+1.18.2
		somanyenchantments: So Many Enchantments Mod 0.2.5
		soulsweapons: Marium's Soulslike Weaponry 0.9.8
		sound_physics_remastered: Sound Physics Remastered 1.18.2-1.0.6
		structory: Structory 1.0.0
		takesapillage: Takes a Pillage 1.0.4
		terrablender: TerraBlender 1.2.0.126
			com_electronwill_night-config_core: core 3.6.4
			com_electronwill_night-config_toml: toml 3.6.4
		torohealth: ToroHealth Damage Indicators 1.18-fabric-2
		travelersbackpack: Traveler's Backpack 1.18.2-7.1.21
		travelerstitles: Traveler's Titles 1.18.2-Fabric-2.1.1
		treeharvester: Tree Harvester 8.0
		trinkets: Trinkets 3.3.1
		twilightforest: The Twilight Forest 4.1.313
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			forge_tags: Forge Tags 2.1
			forgeconfigapiport: Forge Config API Port 3.2.0
			here-be-no-dragons: Here be no Dragons! 1.0.0
			javax_annotation_javax_annotation-api: javax.annotation-api 1.3.2
			mm: Manningham Mills 2.3
			porting_lib: Porting Lib 1.2.630-beta+1.18.2
				serialization_hooks: Serialization Hooks 0.3.23
		waystones: Waystones 10.2.0
		whisperwoods: Whisperwoods 1.18.2-2.1.0
		xaerominimap: Xaero's Minimap 23.2.0
		xaeroworldmap: Xaero's World Map 1.29.2
		yungsapi: YUNG's API 1.18.2-Fabric-2.2.9
			org_javassist_javassist: javassist 3.28.0-GA
			org_reflections_reflections: reflections 0.10.2
		zoomify: Zoomify 1.6.0+build.2
			com_github_llamalad7_mixinextras: mixinextras 0.0.12
			dev_isxander_settxi_settxi-core: settxi-core 2.10.2
			dev_isxander_settxi_settxi-gui: settxi-gui 2.10.2
			dev_isxander_settxi_settxi-kotlinx-serialization: settxi-kotlinx-serialization 2.10.2
	Loaded Shaderpack: (off)
	NEC status: No NEC detected
	Launched Version: fabric-loader-0.14.17-1.18.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce RTX 3070 Laptop GPU/PCIe/SSE2 GL version 3.2.0 NVIDIA 471.41, NVIDIA Corporation
	Window size: 2560x1440
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: Fabric Mods
	Current Language: English (US)
	CPU: 16x 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['destinvanished'/179, l='ServerLevel[New World888]', x=-5492.31, y=84.00, z=-1614.41]]
	Data Packs: vanilla, Fabric Mods
	World Generation: Stable

**Comment by vacla** [comment]
1. You are likely using a mod that is not for 1.18.2
2. You don't even have malilib it seems
