### ISSUE TITLE
Unability to register a keyboard

### ISSUE THREAD

**Issue by berriest** [maruohon/malilib#122]
I ran into a problem after switching to Tweakaroo and MiniHud for 1.19.4 fabric. None of my previously set keybinds were working and i thought, that the problem might be in Super key as in previously appeared issue request. Using ModMenu i accessed the debug feature, and it showed, that keyboard keys were not being registered, meanwhile mouse buttons were. I switched back to 1.19.2 and everything seems to work fine. I tried deleting my config folder, but it had no effect, same with changing fabric-loader and fabric-api versions. I cannot see any way another mod could cause such behavior.  
The bug is not affecting any other game or mod features, just those malilib-dependent keybinds, i also have no idea how to replicate it :(

I'm happy to provide any requested info as installed mods. logs, etc.
malilib v1.15.2
fabric-loader 0.14.19
fabric-api 0.77.0

**Comment by maruohon** [comment]
Apparently a mod called Essential(s?) breaks all malilib-based keybinds in 1.19.4. Do you have that mod installed?

**Comment by berriest** [comment]
Yes, in fact, i do. Thank you for a quick response!
