### ISSUE TITLE
Modrinth support?

### ISSUE THREAD

**Issue by TecEash1** [maruohon/malilib#123]
hey 👋, this library's amazing! Is it possible for this to get modrinth support by any chance? If it could I would appreciate it a lot. Thank you!

**Comment by T1m3sL0v3r** [comment]
due to the Curseforge accident, we have to use other platforms to download mods. if possible, please release mods such as Malilib and Literatica on modrinth. Thank you very much

**Comment by ItzSkyReed** [comment]
https://github.com/maruohon/tweakeroo/issues/418#issuecomment-1513676979

> due to the Curseforge accident, we have to use other platforms to download mods. if possible, please release mods such as Malilib and Literatica on modrinth. Thank you very much

**Comment by SorkoPiko** [comment]
Yes, please add both MaLiLib and Litematica to Modrinth. It has a better API, and is easier to use. I get most of my mods from Modrinth, so if you could add it to Modrinth, it would be highly appreciated.

**Comment by Zoltus** [comment]
Want this also

**Comment by sjansen1** [comment]
Please support modrinth :)

**Comment by CeruleanDerpo** [comment]
+1 for modrinth

**Comment by SorkoPiko** [comment]
can't wait

**Comment by ArkhamCookie** [comment]
Another +1 for Modrinth

**Comment by Fefedu973** [comment]
+1

**Comment by CyanChanges** [comment]
+1

**Comment by notrohit1702** [comment]
https://modrinth.com/mod/malilib

**Comment by TecEash1** [comment]
> https://modrinth.com/mod/malilib

🎉
