### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by hoyy1337** [maruohon/malilib#124]
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2023-04-27 09:18:50
Description: Rendering screen

java.lang.ClassCastException: class fi.dy.masa.minihud.gui.GuiConfigs cannot be cast to class com.plusls.MasaGadget.gui.IDropdownRenderer (fi.dy.masa.minihud.gui.GuiConfigs and com.plusls.MasaGadget.gui.IDropdownRenderer are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @57175e74)
	at fi.dy.masa.malilib.gui.widgets.WidgetListBase.masa_gadget$renderDropdownListAgain(WidgetListBase.java:762)
	at fi.dy.masa.malilib.gui.widgets.WidgetListBase.handler$ckd000$masa_gadget_mod-1_19_4$drawDropDownListAgainBeforeHover(WidgetListBase.java:726)
	at fi.dy.masa.malilib.gui.widgets.WidgetListBase.drawContents(WidgetListBase.java:434)
	at fi.dy.masa.malilib.gui.GuiListBase.drawContents(GuiListBase.java:178)
	at fi.dy.masa.malilib.gui.GuiBase.method_25394(GuiBase.java:172)
	at net.minecraft.class_437.method_47413(class_437.java:121)
	at net.minecraft.class_757.method_3192(class_757.java:937)
	at net.minecraft.class_310.method_1523(class_310.java:1218)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at fi.dy.masa.malilib.gui.widgets.WidgetListBase.masa_gadget$renderDropdownListAgain(WidgetListBase.java:762)
	at fi.dy.masa.malilib.gui.widgets.WidgetListBase.handler$ckd000$masa_gadget_mod-1_19_4$drawDropDownListAgainBeforeHover(WidgetListBase.java:726)
	at fi.dy.masa.malilib.gui.widgets.WidgetListBase.drawContents(WidgetListBase.java:434)
	at fi.dy.masa.malilib.gui.GuiListBase.drawContents(GuiListBase.java:178)
	at fi.dy.masa.malilib.gui.GuiBase.method_25394(GuiBase.java:172)
	at net.minecraft.class_437.method_47413(class_437.java:121)

-- Screen render details --
Details:
	Screen name: fi.dy.masa.minihud.gui.GuiConfigs
	Mouse location: Scaled: (231, 132). Absolute: (462.000000, 265.000000)
	Screen size: Scaled: (463, 265). Absolute: (925, 530). Scale factor of 2.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:937)
	at net.minecraft.class_310.method_1523(class_310.java:1218)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['KiRgIz_u3_aDa'/1, l='ClientLevel', x=10.50, y=-60.00, z=-8.50]]
	Chunk stats: 16384, 3653
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,-60,0), Section: (at 0,4,0 in 0,-4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 55 game time, 55 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:455)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:820)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 2
	Reload reason: manual
	Finished: Yes
	Packs: vanilla, Fabric Mods, essential

-- System Details --
Details:
	Minecraft Version: 1.19.4
	Minecraft Version ID: 1.19.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 513369368 bytes (489 MiB) / 1476395008 bytes (1408 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: 11th Gen Intel(R) Core(TM) i5-11400F @ 2.60GHz
	Identifier: Intel64 Family 6 Model 167 Stepping 1
	Microarchitecture: Rocket Lake
	Frequency (GHz): 2.59
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce GT 1030
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 2048.00
	Graphics card #0 deviceId: 0x1d01
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3168
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 2.93
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 2.93
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 17289.61
	Virtual memory used (MB): 11939.20
	Swap memory total (MB): 9216.00
	Swap memory used (MB): 0.00
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		aqupdhat: Hat command 1.19.4-2.5.0
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
			server_translations_api: Server Translations API 2.0.0-beta.2+1.19.4-pre2
				packet_tweaker: Packet Tweaker 0.3.1+23w06a
		bobby: Bobby 4.0.5
			com_typesafe_config: config 1.4.2
			io_leangen_geantyref_geantyref: geantyref 1.3.13
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		borderlessmining: Borderless Mining 1.1.7+1.19.4
		carpet: Carpet Mod 1.4.101+v230319
		carpet-extra: Carpet Extra 1.4.100
		cem: Custom Entity Models 0.7.3
			completeconfig-base: completeconfig-base 2.3.1
			completeconfig-gui-cloth: completeconfig-gui-cloth 2.3.1
		chunksfadein: Chunks Fade In 1.0.3-1.19.4
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		cloth-config: Cloth Config v10 10.0.96
			cloth-basic-math: cloth-basic-math 0.6.1
		collective: Collective 6.54
		dashloader: DashLoader 5.0.0-alpha.13+1.19.4
			com_github_luben_zstd-jni: zstd-jni 1.5.2-2
			dev_quantumfusion_hyphen: Hyphen 0.4.0-rc.3
			dev_quantumfusion_taski: Taski 2.1.0
		elementa: Elementa 578
		essential: Essential 12266+deploy-staging+g7e25e5ebe
		essential-container: essential-container 1.0.0
			essential-loader: essential-loader 1.0.0
		fabric-api: Fabric API 0.79.0+1.19.4
			fabric-api-base: Fabric API Base 0.4.24+9ff28bcef4
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.25+49abcf7ef4
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.7+348a9c64f4
			fabric-block-api-v1: Fabric Block API (v1) 1.0.6+e022e5d1f4
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.34+c2e6f674f4
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.15+1134c5b8f4
			fabric-command-api-v1: Fabric Command API (v1) 1.2.27+f71b366ff4
			fabric-command-api-v2: Fabric Command API (v2) 2.2.6+e719b857f4
			fabric-commands-v0: Fabric Commands (v0) 0.2.44+df3654b3f4
			fabric-containers-v0: Fabric Containers (v0) 0.1.54+df3654b3f4
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.9+ae0966baf4
			fabric-convention-tags-v1: Fabric Convention Tags 1.4.1+9a7c5daaf4
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.15+aeb40ebef4
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.4.0+6cebf059f4
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.45+7f87f8faf4
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.13+e45f7c65f4
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.43+a1ccd7bff4
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.52+df3654b3f4
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.33+a1ccd7bff4
			fabric-item-api-v1: Fabric Item API (v1) 2.1.17+09a3510cf4
			fabric-item-group-api-v1: Fabric Item Group API (v1) 3.0.5+043f9acff4
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.33+c477957ef4
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.31+df3654b3f4
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.15+5da15ca1f4
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.27+75e98211f4
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.31+9e7660c6f4
			fabric-message-api-v1: Fabric Message API (v1) 5.1.1+1ee8be40f4
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.39+49abcf7ef4
			fabric-models-v0: Fabric Models (v0) 0.3.30+11ba9c3bf4
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.1+a6f3ccfaf4
			fabric-networking-v0: Fabric Networking (v0) 0.3.41+df3654b3f4
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 7.0.3+63b515f4f4
			fabric-particles-v1: Fabric Particles (v1) 1.0.23+f1e4495bf4
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.8+a1ccd7bff4
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.2.0+670e8ac6f4
			fabric-renderer-api-v1: Fabric Renderer API (v1) 2.2.5+81e8c576f4
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.1.1+81e8c576f4
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.38+df3654b3f4
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.28+afca2f3ef4
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.21+f1e4495bf4
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.41+df3654b3f4
			fabric-rendering-v1: Fabric Rendering (v1) 2.1.1+8f878217f4
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.1+e6c7d4eef4
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.2+1e1fb126f4
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.45+8c25edb4f4
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.20+5da15ca1f4
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.9+75e98211f4
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.1.1+da9bb835f4
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 3.0.3+63b515f4f4
		fabric-language-kotlin: Fabric Language Kotlin 1.8.2+kotlin.1.7.10
		fabricloader: Fabric Loader 0.14.19
		ferritecore: FerriteCore 5.2.0
		fpsreducer: FPS Reducer 1.19.4-2.3
		fullbrightnesstoggle: Full Brightness Toggle 3.0
		g4mespeed: G4mespeed 1.3.4
		indium: Indium 1.0.15+mc1.19.4
		isometric-renders: Isometric Renders 0.4.4+1.19.4
			worldmesher: Worldmesher 0.3.0+1.19.3
		java: OpenJDK 64-Bit Server VM 17
		krypton: Krypton 0.2.2
			com_velocitypowered_velocity-native: velocity-native 3.2.0-SNAPSHOT
		lazy-language-loader: lazy-language-loader 0.3.2
		litematica: Litematica 0.14.3
		lithium: Lithium 0.11.1
		magiclib: MagicLib 0.7.293+17aa28c-stable
			magiclib-1_19_4: MagicLib for 1.19.4 0.7.293+17aa28c-stable
		malilib: MaLiLib 0.15.3
		masa_gadget_mod: Masa Gadget 3.1.289+1ca4352-stable
			masa_gadget_mod-1_19_4: Masa Gadget for 1.19.4 3.1.289+1ca4352-stable
		memoryleakfix: Memory Leak Fix 1.0.0
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.6
		minecraft: Minecraft 1.19.4
		minihud: MiniHUD 0.26.2
		namepain: Name Pain 1.4.0
		no-resource-pack-warnings: No Resource Pack Warnings 1.2.0
		no-telemetry: No Telemetry 1.7.0
		nochatreports: No Chat Reports 1.19.4-v2.1.1
		notenoughcrashes: Not Enough Crashes 4.4.0+1.19.4
		org_jetbrains_annotations: annotations 13.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.10
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.10
		org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.2
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
		org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.3
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.3
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.3
		owo: oωo 0.10.3+1.19.4
			blue_endless_jankson: jankson 1.2.2
		reeses-sodium-options: Reese's Sodium Options 1.5.0+mc1.19.4-build.72
		sit: Sit 1.19.4-23
		smoothboot: Smooth Boot 1.19.4-1.7.0
		sodium: Sodium 0.4.10+build.24
		sodium-extra: Sodium Extra 0.4.18+mc1.19.4-build.100
			caffeineconfig: CaffeineConfig 1.1.0+1.17
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
		starlight: Starlight 1.1.1+fabric.ae22326
		tweakeroo: Tweakeroo 0.16.0
		universalcraft: UniversalCraft 262
		viafabric: ViaFabric 0.4.10+33-dev
			org_yaml_snakeyaml: snakeyaml 2.0
			viafabric-mc119: ViaFabric for 1.19 0.4.10+33-dev
			viaversion: ViaVersion 4.7.0-23w14a-SNAPSHOT
		vigilance: Vigilance 278
		worldedit: WorldEdit 7.2.14+6360-094b734
		worldeditcui: WorldEditCUI 1.19.4+01
	Launched Version: fabric-loader-0.14.19-1.19.4
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce GT 1030/PCIe/SSE2 GL version 3.2.0 NVIDIA 531.68, NVIDIA Corporation
	Window size: 925x530
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, fabric
	Current Language: ru_ru
	CPU: 12x 11th Gen Intel(R) Core(TM) i5-11400F @ 2.60GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['KiRgIz_u3_aDa'/1, l='ServerLevel[NewWorld]', x=10.50, y=-60.00, z=-8.50]]
	Data Packs: vanilla, fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: Minecraft (minecraft), Masa Gadget for 1.19.4 (masa_gadget_mod-1_19_4), Fabric Loader (fabricloader), MaLiLib (malilib)

**Comment by maruohon** [comment]
Looks like a MasaGadget bug of some kind.

**Comment by hoyy1337** [comment]
Yeah, i deleted this mod and minihud stop crashing, thank you.
