### ISSUE TITLE
version documentation

### ISSUE THREAD

**Issue by KittyBoiUwU** [maruohon/malilib#138]
Is there any way you could provide documentation about which parts of the files would need to be modified for minor version updates (1.20.x - 1.20.x)

**Comment by KittyBoiUwU** [comment]
Alongside where you get your version info when updating

**Comment by maruohon** [comment]
The version info comes from here: https://fabricmc.net/develop/

There is no way for me to predict what Mojang changes in each version and thus what would need to be modified and updated. If they make no code changes that break my mods, then you don't need to do anything to update, you can keep using the previous mod versions.

... Except if I have set a strict MC version dependency. But I usually don't do that forward for minor versions as I can't know beforehand when something would break. That version dependency for the Fabric versions of the mods is in the `fabric.mod.json` file inside the `resources` directory. If that ever is the only change needed, then you can just extract that file from the mod jar (with 7-zip or whatever) and modify it and then drag it back in to update it, without actually needing to re-build the mod from source.

**Comment by KittyBoiUwU** [comment]
> The version info comes from here: https://fabricmc.net/develop/
> 
> There is no way for me to predict what Mojang changes in each version and thus what would need to be modified and updated. If they make no code changes that break my mods, then you don't need to do anything to update, you can keep using the previous mod versions.
> 
> ... Except if I have set a strict MC version dependency. But I usually don't do that forward for minor versions as I can't know beforehand when something would break. That version dependency for the Fabric versions of the mods is in the `fabric.mod.json` file inside the `resources` directory. If that ever is the only change needed, then you can just extract that file from the mod jar (with 7-zip or whatever) and modify it and then drag it back in to update it, without actually needing to re-build the mod from source.

**Comment by KittyBoiUwU** [comment]
Thank you for the information
