### ISSUE TITLE
MaLiLib not compatible with some mods in this modpack

### ISSUE THREAD

**Issue by AaronPesch** [maruohon/malilib#143]
Hi, 
I'll just send the curseforge threat in here so you can follow along what the problem is: 
https://forums.minecraftforge.net/topic/142758-the-mod-file-ccurseforgeminecraftinstancesescamodpackmodsmafglib-015-mc1201jar-has-mods-that-were-not-found/#comment-563505
Basically MaLiLib is not compatible with some mods from the modpack, neither installing manually (and older versions) worked and curseforge just does not register it at all.
Here is the log: https://paste.ee/p/4ExQv
Hope you have any ideas on how to fix this.
Aaron

**Comment by vacla** [comment]
@AaronPesch there is no official 1.20.1 malilib for (neo)forge yet, you should best contact the author who made the port.
