### ISSUE TITLE
The mod is giving an error

### ISSUE THREAD

**Issue by amopudim** [maruohon/malilib#167]
Error: 

### Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'MaLiLib' (malilib) 0.21.1 with any version that is compatible with:
		 - minecraft 1.21.3
More details:
	 - Mod 'MaLiLib' (malilib) 0.21.1 requires any version between 1.21 (inclusive) and 1.21.1 (inclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.3! ###

The mod is giving an error even though it says it's compatible in the mod description and website. As in the image. I want to use the mod in 1.21.3

Message from the mod/website description: "Merge code from Development branches (1.21.3+)"

![Screenshot 2024-11-15 123401](https://github.com/user-attachments/assets/f4f62553-5bdc-4d48-9c10-8042c5a21772)

**Comment by sakura-ryoko** [comment]
The "Merge Code" message means that the code from 1.21.3 versions, and DEV branches were synchronized with 1.21/1.21.1's code.

**Comment by sakura-ryoko** [comment]
If you need 1.21.3, download the 1.21.3 version from my GitHub.  It will be available soon enough on Modrinth.
