### ISSUE TITLE
Malilib crash on startup with fabric 1.15.2

### ISSUE THREAD

**Issue by Jiriki79** [maruohon/malilib#17]
when i load up fabric with just the api and malilib it craft before even getting to the title screeen
[latest.log](https://github.com/maruohon/malilib/files/4462852/latest.log)

**Comment by vacla** [comment]
you need to update your malilib, it could be you are also using the one from a wrong version

**Comment by Jiriki79** [comment]
im am using the lastest one of everything

**Comment by vacla** [comment]
Get latest from here: https://masa.dy.fi/tmp/minecraft/mods/client_mods/?mcver=1.15.2

**Comment by Jiriki79** [comment]
ive been using curseforge for all my mods

**Comment by vacla** [comment]
weird since the latest one on curseforge is arne.6 and you have arne.2

**Comment by eatmyvenom** [comment]
> ive been using curseforge for all my mods

Given that these mods are in early stages of development, curseforge is not where to get the latest version, refer the the link @vacla provided for the latest builds

**Comment by Jiriki79** [comment]
i used the link and minecraft did launch but the mods were not loaded
like i installed litematica and tweakaroo and under the controls setting there is nothing to be able to know that they are loaded

**Comment by vacla** [comment]
tweakeroo control is X + C
litematica controls is M + C

**Comment by Jiriki79** [comment]
ill test and see

**Comment by Jiriki79** [comment]
they loaded thank you
