### ISSUE TITLE
Failed to launch

### ISSUE THREAD

**Issue by Zeptic56** [maruohon/malilib#18]
In the fabric launcher, there's an error listed : "mod litematica depends on mod {malilib @ [>=0.10.0-dev.19]}, which is missing!". Theres no download for the dev.19 only 20. Could I get a fix for this?

**Comment by vacla** [comment]
You need dev.20 but you are probs using a wrong version, can you list the versions of litematica and malilib?

**Comment by CannibalHamst3rs** [comment]
could the problem be that litematica 1.15.2 is for fabric launcher but the only version of 1.15.2 malilib is for forge?

**Comment by eatmyvenom** [comment]
> could the problem be that litematica 1.15.2 is for fabric launcher but the only version of 1.15.2 malilib is for forge?

Thats incorrect there are versions for both fabric and forge if you look at the files tab. Also try looking here https://masa.dy.fi/mcmods/client_mods/ for the mods as its easier to use than cf imo.

**Comment by nysquidz** [comment]
I have the same issue, is there a fix yet?

**Comment by vacla** [comment]
@nysquidz in the link posted above you can get the right version, on curseforge it is also correct

**Comment by maruohon** [comment]
Since there are now both Fabric and Forge versions, you need to pay attention to download the correct version from CurseForge. The mod loader name and the minecraft version are always in the mod file name.

**Comment by nysquidz** [comment]
@vacla @maruohon Im new to fabric, i assumed it when in the .fabric folder not the mods folder like an idiot, whoops :P

**Comment by PG7891** [comment]
I am having this same issue. I at first accidentally launched the with the forge version installed and got this error but after I tried each of the other 3 options that are 1.15.2 fabric but no matter what I do I keep getting this issue. I have a suspicion that somehow the first download mistake I did is sticking around somehow and causing this to happen over and over. Any suggestions?

**Comment by vacla** [comment]
@PG7891 can you show your mods directory?

**Comment by maruohon** [comment]
@PG7891 Can you screenshot your mods folder (so that the mod file names/versions are visible) or list the exact mod versions you are using? Or pastebin the crash log. Assuming you are using Fabric, you can get the latest mod versions from here for your MC version: https://masa.dy.fi/mcmods/client_mods/

**Comment by maruohon** [comment]
I assume these issues have been solved long ago due to no responses.
