### ISSUE TITLE
Forces sneak when manipulating inventory

### ISSUE THREAD

**Issue by mll34400** [maruohon/malilib#3]
The problem persists without any of the dependent mods.  The library is the issue.

**Comment by maruohon** [comment]
I've heard this from multiple people recently, but this hasn't happened to me, which is strange... Are there any specific steps to reproduce this?

* Does it happen every time for you? Is it every time after you shift + click to move items?
* Are you on MC 1.12.x or 1.13.x?
* Do you have Forge if you are on 1.12.x?
* Which keyboard layout do you use? (QWERTY etc.)

**Comment by skyrising** [comment]
- Yes seems like every time I shift click
- 1.12
- No Forge
- QWERTZ (German, no dead keys)

**Comment by mll34400** [comment]
50% of the time.
Yes.
1.13.2
Vanilla
QWERTY
