### ISSUE TITLE
malilib isnt working

### ISSUE THREAD

**Issue by Infra03** [maruohon/malilib#52]
i installed MiniHUD and malilib but nothing works and idk what to do, please help

**Comment by vacla** [comment]
Try pressing H + C , if that works, malilib also works

**Comment by Infra03** [comment]
i tried but nothing happened.
maybe i put the mod in the wrong folder?

**Comment by maruohon** [comment]
Did you successfully install Fabric? (Does it say Fabric in the bottom left of the Minecraft main menu, or at the top of the F3 screen?) Once Fabric is working, you just put the mods to the `.minecraft/mods/` directory (which Fabric will create for you when you launch the game, if it didn't exist already).

**Comment by Infra03** [comment]
ok it works now! thank you so much!
