### ISSUE TITLE
Could not find required mod: litematica requires {malilib @ [>=0.10.0-dev.24]}

### ISSUE THREAD

**Issue by SynergySam** [maruohon/malilib#54]
Whenever I try to open up Litematica, it says this. I already have Malilib 1.16.5 installed but this shows up when I launch the mod.

**Comment by Crec0** [comment]
get latest malilib from https://www.curseforge.com/minecraft/mc-mods/malilib/files

**Comment by maruohon** [comment]
You are then also using the wrong mod version for the MC version. The Litematica version that requires malilib `dev.24` is the latest 1.17.1 version, but you said you are using malilib for 1.16.5? Which MC version are you in even? Just get the latest version of both mods **for the correct MC version** from CurseForge, from the Files page for each mod.
