### ISSUE TITLE
[1.17.1] Some keystrokes are not processed after switching the language (Win+Space)

### ISSUE THREAD

**Issue by Felix14-v2** [maruohon/malilib#55]
**Description**
The keyboard shortcuts responsible for opening the GUIs and performing some functions stop working after switching the language by pressing Win+Space (Alt+Shift is fine). Refocusing on the game window solves the problem.
[[Demo]](https://youtu.be/MbRmYEYdKZg)

**Technical**
Litematica v0.0.0-dev.20210713.103711
Malilib v0.10.0-dev.24

[logs](https://github.com/maruohon/malilib/files/7092584/latest.log), if needed.

**Comment by maruohon** [comment]
In the demo video it looks like the Win key is left stuck? So pressing it once should unstuck it? There is nothing I can do in the mod to fix them getting stuck (if the LWJGL library does not receive the key release event, then it thinks it's still being held down).

But in the main development code I have already changed all of the hotkeys to allow extra keys by default. So once the rewrites in 1.12.2 are finished and ready to be ported forward, that will become the new default setting. You can change that already manually via the Advanced Keybind Settings for each hotkey, where it not allowing extra keys is problematic.

**Comment by Felix14-v2** [comment]
Hm, this is completely solve my problem :)
![image](https://user-images.githubusercontent.com/75726196/132954576-0184ba15-209d-4446-bad4-09862a48844c.png)
