### ISSUE TITLE
Malilib crashes the game

### ISSUE THREAD

**Issue by DreamsForMe** [maruohon/malilib#61]
When i try to launch the game with malilib the game crashes but when i take it off it says i need a sertain version. Its says i need ver22 but there is no download for it and it doesn't work with any other version and it crashes.

**Comment by DreamsForMe** [comment]
when i try to load it with it crashes but without it gives the error 
net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install malilib 0.10.0-dev.22 (later versions might work too).
Unmet dependency listing:
	 - Mod 'Item Scroller' (itemscroller) requires "version 0.10.0-dev.22 or later" of malilib, which is missing!
	at net.fabricmc.loader.impl.discovery.ModResolver.findCompatibleSet(ModResolver.java:140)
	at net.fabricmc.loader.impl.discovery.ModResolver.resolve(ModResolver.java:41)
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:197)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:183)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:119)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by Jorianv** [comment]
the latest version is dev 26 and van be found here https://www.curseforge.com/minecraft/mc-mods/malilib/files

**Comment by maruohon** [comment]
Update all the mods to the latest version available on CurseForge. And make sure you get the mods for the correct MC version. On the Files page on CurseForge, look at the Game Version column, and also the mod file name will have the target MC version in it as the first number.

**Comment by DreamsForMe** [comment]
ive tried every version and it crashes when i use them

**Comment by DreamsForMe** [comment]
all of my things are for 1.17 with the correct fabric loader version

**Comment by DreamsForMe** [comment]
I figured it out, it was clashing with sodium and entity culling. Thanks for the help

**Comment by TheoCGaming** [comment]
> I figured it out, it was clashing with sodium and entity culling. Thanks for the help

Will there eventually be a fix for these clashes in a later version? My computer is very slow and needs those mods to run playably!

**Comment by maruohon** [comment]
@TheoCGaming AFAIK there should be no issues with Sodium. I haven't heard of anything from my "close circle" and also it seems to work fine in my test instances. And looks like Entity Culling is also enabled by default and works fine in my test instance. If there is an issue, then I need more information and crash logs or something to go by. Currently my stance is that there is no issue with Sodium.

**Comment by TheoCGaming** [comment]
The issue is... there *are* no crash logs when the game crashes on my end. I think I can dig a normal log up, though...

**Comment by TheoCGaming** [comment]
[2021-11-30-5.log](https://github.com/maruohon/malilib/files/7783050/2021-11-30-5.log)

I think this is it?
also my cursor disappeared, strange...

**Comment by maruohon** [comment]
You seem to have a number of 1.17 mod versions even though you are trying to launch 1.18. Update all your mods to the 1.18 versions, or if there isn't one, then take out the mod.

**Comment by TheoCGaming** [comment]
Alright, I'll update everything and tell you if it fixes anything.

**Comment by TheoCGaming** [comment]
malilib works now :D
