### ISSUE TITLE
Impossible to use MaLiLib in CurseforgeApp

### ISSUE THREAD

**Issue by Akorian** [maruohon/malilib#68]
When trying to install MaLiLib to a 1.18.1 Fabric Modpack within the Curseforge App, the mod doesn't show up in search. I used the mod a fair time now on 1.18.1 since some of my other mods depend on it. So I think MaLiLib wasn't correctly labeled on Curse which makes it impossible for app users to find it in such situations.

**Comment by maruohon** [comment]
I uploaded a new round of 1.18.1 mod releases today.
