### ISSUE TITLE
MaLiLib0.12.0 needs to be replaced with version 0.12?

### ISSUE THREAD

**Issue by warypumpkin** [maruohon/malilib#77]
Hello, I'm trying to use the Fabric Minecraft mods Litematica and MaLiLib for 1.18.2, however, I get this:

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'MaLiLib' (malilib) 0.12.0 with any version between 0.11.0 (inclusive) and 0.12 (exclusive).
Unmet dependency listing:
	 - Mod 'Litematica' (litematica) 0.10.2 requires any version between 0.11.0 (inclusive) and 0.12 (exclusive) of mod 'MaLiLib' (malilib), but only the wrong version is present: 0.12.0!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

Any help or advice is appreciated!

**Comment by Coathar** [comment]
Update to the latest version of Litematica which  is 0.11.0 
https://www.curseforge.com/minecraft/mc-mods/litematica/files/
