### ISSUE TITLE
ERROR BUG! 1.18.2 Fabric not found config. It's not exists. Dont open the gui main.

### ISSUE THREAD

**Issue by tianxiu2b2t** [maruohon/malilib#81]
Mod is working. I not found any file. Please fix this bug!

**Comment by vacla** [comment]
There is not much information to go from, this is just a library the mods can use, the config exists under /config/malilib.json

**Comment by tianxiu2b2t** [comment]
But I remember add "Tweakroo" mod. So thank you for telling me can using normal.



在 2022-04-10 16:58:12，"vacla" ***@***.***> 写道：

There is not much information to go from, this is just a library the mods can use, the config exists under /config/malilib.json
