### ISSUE TITLE
gradlew build: Failed to apply plugin 'net.minecraftforge.gradle.liteloader'.

### ISSUE THREAD

**Issue by gavmor** [maruohon/malilib#88]
Following README.md, I ran `gradlew build` and received this error:

```
FAILURE: Build failed with an exception.

* Where:
Build file '/workspace/malilib/build.gradle' line: 19

* What went wrong:
A problem occurred evaluating root project 'malilib'.
> Failed to apply plugin 'net.minecraftforge.gradle.liteloader'.
   > Configuration with name 'compile' not found.
```
[Here is a Gradle Build Scan](https://scans.gradle.com/s/edqcrq7ekd3ly) showing the error.

**Comment by maruohon** [comment]
Looks like you are trying to build the LiteLoader branch. You need to use Java 8 for that, as the old 1.12.2 tool chain doesn't work with Java 9+ (AFAIK). Also I'm not sure how recent Gradle versions that toolchain still works with, but I've just been using the old 2.14.1 version, which the `gradle/wrapper/gradle-wrapper.properties` file in the LiteLoader branch should still be set to.

**Comment by gavmor** [comment]
Oh, I don't particularly care to build LiteLoader, I misunderstood it to be equivalent to `main`. I'm principally interested in the latest, so I'll try the `fabric_1.19.x_early_port_2` branch.
