### ISSUE TITLE
malilibib 13.0 needs to be replaced with any 0.12.x version

### ISSUE THREAD

**Issue by Pearl8520** [maruohon/malilib#90]
i think this is the same occurrence as [issue #77](https://github.com/maruohon/malilib/issues/77) though when i do replace version 0.13.0 witth 0.12.1 for example, its incompatible as its only compatible with the minecraft version 1.18.2 where as im on version 1.19.0
pictures of the errors attached as references
![image](https://user-images.githubusercontent.com/35458274/181504743-3e323a61-8123-4fee-8850-0177bc680d29.png)
![image](https://user-images.githubusercontent.com/35458274/181504777-6ed14e78-835d-4ebb-933f-f38405979c62.png)

**Comment by maruohon** [comment]
This was an issue of mixing the community ports of the mods with the later official releases, which just have the version numbers and requirements set differently.
