### ISSUE TITLE
<html>Mod 'MaLiLib' (malilib) 0.13.0 requires any version between 1.19.1 (inclusive) and 1.20 (exclusive) of 'Minecraft'<br>(minecraft), but only the wrong version is present: 1.19!</html>

### ISSUE THREAD

**Issue by Pre1213** [maruohon/malilib#91]
![image](https://user-images.githubusercontent.com/110891669/183594652-9971e559-9af7-4e63-b80b-9e8d4bac9e12.png)

**Comment by kosma** [comment]
Don't mix versions between 1.19/1.19.1 and between community and official.
