### ISSUE TITLE
Hi Malilib forge version everytime I start up it comes up a error message

### ISSUE THREAD

**Issue by keatonkdk** [maruohon/malilib#93]
The error message says Game crashed... An unexpected issue occured and the game has crashed. We're sorry for the inconvenience... This crash may be caused bt an invalid java runtime configuration. Check any custom configuration settings. Exit code 1. When I delete the mod from the folder the game starts up fine please help.

**Comment by maruohon** [comment]
This doesn't tell me anything, you didn't even mention the MC version you are on. Please post the crash log from `.minecraft/crash-reports/` or the `.minecraft/logs/latest.log` file to a pastebin service and link it here.
