### ISSUE TITLE
[Fabric 1.19 port 3] Tooltip of keybind settings is rendering weird

### ISSUE THREAD

**Issue by maxsupermanhd** [maruohon/malilib#95]
![image](https://user-images.githubusercontent.com/20772987/187858436-2f9a78b2-c97b-48d7-bcbc-962c341d8af9.png)

My take is that it is missing a texture, but that's just a guess

Version: Fabric 1.19.2 0.54.0.2 (from maven)

**Comment by maruohon** [comment]
This should be fixed in the repo (here: 9db4645dcc60aaf2763562389de896cc1a0a814f), but if you are running an earlier build, like the one from my maven, then it doesn't have that commit yet.
