### ISSUE TITLE
ERROR GAME Crashed

### ISSUE THREAD

**Issue by MrKubilas** [maruohon/malilib#97]
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'fabric-networking-api-v1'!

**Comment by maruohon** [comment]
Post the crash log or `.minecraft/logs/latest.log` file to some pastebin service. This isn't enough information to know anything about he cause yet. One obvious thing is to check that you have the mod (all the mods) for the correct MC version.
